development:
  adapter: postgresql
  encoding: unicode
  database: parkit_development
  host: localhost
  pool: 5
  username: deployment
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: parkit_test
  host: localhost
  pool: 5
  username: deployment
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: parkit
  host: localhost
  pool: 5
  username: deployment
  password: password1
