development:
  adapter: postgresql
  encoding: unicode
  database: chargeit_development
  host: localhost
  pool: 5
  username: deployment
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: chargeit_test
  host: localhost
  pool: 5
  username: deployment
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: chargeit
  host: localhost
  pool: 5
  username: deployment
  password: password1
