default: &default
  adapter:  postgresql
  encoding: unicode
  username: timproctor
  pool:     5
  timeout:  5000

development:
  adapter: postgresql
  host: localhost
  username: timproctor
  database: app-dev

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
