default: &default
  adapter:  postgresql
  encoding: unicode
  username: timproctor
  pool:     5
  timeout:  5000

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: deployment
  database: myapp_development
  pool: 5
  password: passwod1

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
