default: &default
  adapter:  postgresql
  encoding: unicode
  username: timproctor
  pool:     5
  timeout:  5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
